### ISSUE TITLE
The emulator crashes during the installation of the Bloodborne PKG file.

### ISSUE THREAD

**Issue by Laciffo** [shadps4-emu/shadPS4#1057]
Good afternoon, I had an error when selecting a PKG file through the bloodborne emulator crashes I would like to know why and is there a solution? 
My configuration: 
Processor- Intel Xeon e5-2650 v2
Graphics processor-RTX 2060, 6GB vram
The amount of RAM is 32 GB HyperX fury
Please help me because I really want to try this masterpiece! If the problem is in the hardware, is there a way out without replacing the configuration?

**Comment by elxkot** [comment]
I had simmilar issue with prebuilt binary. I assume is because it's compiled for newer architecture. So i compiled my own binaries from master branch and it kind of works: PKG's install, but don't launch because my CPU is too old apearently. I have pretty similar CPU as your's: Xeon E5-1650, which is 2nd Gen Sandy Bridge, as of yours is 3rd Gen Ivi Bridge, which is slightly newer, but prety much the same except lower power consumption. As far as i dig in issue reports, there is no luck in launching games on CPUs older than Broadwell architecture for now at least :(

**Comment by Laciffo** [comment]
Well, thank you for answering my question!
