### ISSUE TITLE
im getting a black screen

### ISSUE THREAD

**Issue by changenickname** [shadps4-emu/shadPS4#1082]
i open the game and it doesnt load. it gives a wall of "[Core.Linker] <Error> linker.cpp:Resolve:298: Linker: Stub resolved" followed by letters and then it says "[Core] <Error> stubs.cpp:UnknownStub:30: Returning zero to"  followed by numbers. anyone knows how to fix this?

**Comment by changenickname** [comment]
tinkered and its grey now and the wall doesnt stop

**Comment by changenickname** [comment]
IT LIVES

**Comment by changenickname** [comment]
it died

**Comment by pjungkamp** [comment]
This is not really how you should report an issue.

Can you please give the issue a proper description and name. Tell us the exact game you're starting, the version of `shadps4` you're using, as well as relevant information about your system (e.g. Windows/MacOS/Linux Distro). Please add the log file for the game that isn't working as a text file to the issue instead of just pasting a part of it in your text. A screenshot of the problem wouldn't hurt either.

Comments like "tinkered" and "it lives" don't really tell us anything.... Can you please put a little effort in?

**Comment by changenickname** [comment]
hi sorry it was late and i was tired trying to get it working all night but i think ive figured it out.
again im sorry about that

**Comment by StevenMiller123** [comment]
If you've resolved your issue, please close this report.
