### ISSUE TITLE
shadps4 out of device memory on bloodborne. 

### ISSUE THREAD

**Issue by Dictavios** [shadps4-emu/shadPS4#1151]
Last build tried (), my rig has 16gb of ram and my gpu 8gb vram. I'm using msi afterburner to check the memory use and the emu crashes when vram and ram are not even full filled. ram goes as high as 13gb and vram 7gb. I'll share the log. Used 720p patch, no sfx folder. Tried the 360p patch and same results despite lower ram and vram usage.
I5 10400f
rx 6600 8gb
16gb ram
 
![1](https://github.com/user-attachments/assets/3a0d8a43-3856-4c03-8e69-f06be8a20649)

[shad_log.txt](https://github.com/user-attachments/files/17179575/shad_log.txt)

**Comment by purgea** [comment]
Your GPU VRAM has reached 7GB and what happened is that the emulator tried to allocate another buffer and failed to do so because of the lack of memory, there is a difference between memory allocation and memory consumption, if any piece of software fails to allocate memory, it will throw an exception.

Basically, your GPU (mine as well) has 8GB VRAM which at this point is not ideal, you will need to restart the emulator after every few warps and deaths due to the memory leaks being present because of the sfx (mostly)

**Comment by Dictavios** [comment]
Thanks for the reply. Thing is that even on 360p patched, which uses no more than 6gb, crashes the same. Ive seen videos of the game running on 7gb vram on way less powerful gpus such as 1050ti.

**Comment by Hermiten** [comment]
Duplicate of https://github.com/shadps4-emu/shadPS4/issues/498
