### ISSUE TITLE
Bloodborne keeps crashing!

### ISSUE THREAD

**Issue by lolleri200** [shadps4-emu/shadPS4#1158]
Please help me I have tried to get Bloodborne working on my PC for over a week. I have tried different Emulator settings, patches and mods, but nothing seems to work. The game just crashes after the loading screen and I did managed to get in game only with 360p resolution and walk a bit in Central Yharnam after leaving Hunter's dream and then the game just crashed again and I haven't been able to get past the loading screen...
PC Specs:

CPU:  AMD Ryzen 7 5700X3D
GPU: Nvidia RTX 3070 (8 Gb VRAM)
RAM: 32 Gb (DDR4)
[shad_log.txt](https://github.com/user-attachments/files/17180954/shad_log.txt)

Does anyone has a clue what I am doing wrong please helps? Here is also my log file.

**Comment by CanEHdianboi** [comment]
Did you download the BloodBorne Patch for 1.09? I Found that fixed it for me.

**Comment by lolleri200** [comment]
Hi, yes I have installed the 1.09 patch already.

**Comment by lolleri200** [comment]
<img width="570" alt="image" src="https://github.com/user-attachments/assets/b31c7a38-d836-41a3-84e9-79acff928129">

**Comment by Dictavios** [comment]
Im experiencing same issue, but you have way more ram and vram than me. It doesnt make sense.

**Comment by redkoom** [comment]
same i try some mods still not working . game and shadps4 crash when i open bloodborne

**Comment by dante42lk** [comment]
Same, most of the time i get this error when any 3d scene tries to load:

`[Lib.Http] <Error> http.cpp:sceHttpWaitRequest:585: (STUBBED) called
[Lib.Http] <Error> http.cpp:sceHttpWaitRequest:585: (STUBBED) called
[Render.Vulkan] <Error> tile_manager.cpp:TryDetile:394: Unsupported tiled image: R32Sfloat (Depth_MacroTiled)
[Render.Vulkan] <Error> tile_manager.cpp:TryDetile:394: Unsupported tiled image: R32Sfloat (Depth_MacroTiled)
[Kernel] <Info> libkernel.cpp:sceKernelGetCompiledSdkVersion:258: returned system version = 0x4500000`

There are lots of http.cpp:sceHttpWaitRequest:585:  as well

**Comment by Iamsolazyforthis** [comment]
Same here. I tried a lot of builds, mods and drivers, and nothing changes. I noticed that the crash occurs when the video memory is full. If you start a new game, there are no crashes. Also, if you exit the game and log back into Hunters Dream, the crash does not occur. Even if after that I teleport to the first respawn bonfire. Even if I reach the second bonfire then the crash does not occur. However, if you immediately appear at the second bonfire upon entering the game, then the memory is not enough only at the end of loading. Sometimes the game did not crash even after the memory was completely filled during loading, but then my VRAM was only half full. It seems to me that the problem is that, when you immediately load into a large open area that requires a lot of VRAM, the game crashes, because it does not have time to load everything at once. But if you fill it gradually, then everything will be fine. I hope that the developers will notice this problem and I will be very happy and grateful if they can solve this problem. Judging by the discord, reddit and GitHub, this is a very common problem. To all who are trying to fix this problem, I advise you to reinstall the drivers for the video card and C++. Try different game images, different builds and mods as this helped some.

My specs:
CPU: AMD Ryzen 7 5600G
GPU: Nvidia RTX 3060 Ti (8 Gb VRAM)
RAM: 16 Gb (DDR4)

**Comment by rafael-57** [comment]
You're running out of device memory. 

[Tty] <Info> libkernel.cpp:ps4__write:221: == Stall during rendering at flush 1
[Debug] <Critical> buffer.cpp:operator():87: Assertion Failed!
Failed allocating buffer with error ErrorOutOfDeviceMemory

These crashes will take a while to fix, the emu will be eventually more optimized and consume less memory.

**Comment by Hermiten** [comment]
Duplicate of https://github.com/shadps4-emu/shadPS4/issues/946

**Comment by Hermiten** [comment]
Duplicate of https://github.com/shadps4-emu/shadPS4/issues/498

**Comment by yMasteer** [comment]
[Debug] <Critical> tile_manager.cpp:operator():370: Assertion Failed!
