### ISSUE TITLE
Audio Breakage In Certain Contexts Without Sysmodules (Bloodborne 60FPS)

### ISSUE THREAD

**Issue by IAmBatby** [shadps4-emu/shadPS4#1189]
This is less of a real problem since having your sysmodules correctly dumped should be a required step in using ShadPS4 but using this issue to document the behavior regardless.

When playing Bloodborne with legally re-packaged .fsb files to correctly play audio, using Lance McDonald's 60fps patch will consistently break audio when sysmodules are not installed. Running the game without the patch at 30fps makes audio work as intended and after installing sysmodules audio works as intended at the patched 60fps.

**Comment by petermeierrr** [comment]
I noticed that many sounds (footsteps, weapon clinging, enemy voices) don't play when you start the game off a crash, so that you get the initial "please end the game properly" warning. If you load the save and quit then to main menu and leave, sound will play again.
After your post I tried this with and without the sys_modules and the behaviour is the same.
Once I understood above logic, I had no problems anymore in-game with the currently recommended "scissor rects" build.

**Comment by IAmBatby** [comment]
This is unrelated to that issue

**Comment by conradojv** [comment]
I'm having the same issue. How can I fix it? Do I have to download "sys_modules"? How do I download? There are many questions.

**Comment by Hermiten** [comment]
Hello, for now we only support version on this GitHub and without patches. I'm closing this one for not planned
