### ISSUE TITLE
Bloodborne crushes while loading save

### ISSUE THREAD

**Issue by PrimalSmite** [shadps4-emu/shadPS4#1284]
The game crushing while you press Continue button, wait for loading screen and start the game. After 2-3 seconds game crushing with logs:

[shad_log.txt](https://github.com/user-attachments/files/17283723/shad_log.txt)

**Comment by Litnesslegitimate** [comment]
The last two lines:
"[Debug] <Critical> buffer.cpp:operator():87: Assertion Failed!
Failed allocating buffer with error ErrorOutOfDeviceMemory"
mean that your GPU ran out of VRAM if I'm not mistaken

This happens to me when I quit (Or crash) in certain areas then try to load back in. (I assume it might just be trying to load in too much at once, I only have 10G VRAM so it would track). 
What would usually work for me is enabling the 360P patch (Maybe disabling the 60 fps patch too?) and heading back to the hunters dream, then restarting the emu from there 
(Edit you can set your patches back after getting to the dream)
 
If it's really bad I've had a little luck with also making the window small on top of that, but I've def had to delete my save file a few times because the game ends in a bad spot
