### ISSUE TITLE
Blackscreen on Bloodborne upon launch on Arch Linux with CachyOS kernel

### ISSUE THREAD

**Issue by Lop14** [shadps4-emu/shadPS4#1322]
[shad_log.txt](https://github.com/user-attachments/files/17319936/shad_log.txt)

Tried with multiple emulator versions, forks, patches and mods. Same errors persist. I was able to run it until a few weeks ago, however, if that information is of any value. 

OS: Arch Linux x86_64
Kernel: Linux 6.11.2-5 cachyos
WM: Hyprland (Wayland)

CPU: AMD Ryzen 5 5600
GPU: AMD RX 6600 XT
RAM: 32Gb DDR4 3600MHz
Vulkan: 1.3.289 - radv [Mesa 24.2.4-arch1.2]

**Comment by StevenMiller123** [comment]
Bloodborne never booted on Linux without hacked builds. A fix for this issue is still in the works.

**Comment by Lop14** [comment]
> Bloodborne never booted on Linux without hacked builds. A fix for this issue is still in the works.

Nah, I was able to boot before on main branch build. Thx for quick reply on the current issue tho.

**Comment by Shoegzer** [comment]
Also encountering difficulties with shadPS4 crashing on loading this title.  Tested on Linux Mint 22.

@StevenMiller123 which PR are you referring to that addresses this?  I couldn't find it on this repo.

**Comment by StevenMiller123** [comment]
@Shoegzer The fix for Bloodborne on Linux is not PR'ed yet, but will likely come as part of the WIP libkernel rewrite stored in the more-kernel branch. Note that this branch does not compile, and is far from completion.

The details on Bloodborne's Linux-specific issue are shared frequently in the discord server, you can search in there if you want technical details on the issue (and the hack that people currently use to bypass this issue).

**Comment by Shoegzer** [comment]
Thanks for your helpful explanation.  I'll wait for a proper fix via the libkernel rewrite, good to know it's being looked into.

**Comment by Hermiten** [comment]
Some others issues is related to this. This one is newer than others so I'm closing it.
