### ISSUE TITLE
FPS counter keybinding (F10) should be added to README

### ISSUE THREAD

**Issue by kalaposfos13** [shadps4-emu/shadPS4#1362]
As far as I know, it isn't mentioned anywhere, and it is a very useful thing to know
Also there is rdoc capture on F12 whatever that means

**Comment by GHU7924** [comment]
I know:
F10 - FPS counter
Ctrl+F10
F11 - Fullscreen
there are more, but I don't remember them))

I think it's worth making a separate item in the "Help" section, which will display a list of available commands (which is similar to "About shadPS4"), only a window similar to something like this will be displayed:
(An image from the Internet for example)
![Screen-Shot-2014-05-16-at-7 22 04-AM-4109755284](https://github.com/user-attachments/assets/746f8154-443f-44e7-a65a-2ba4952c5e73)

It is also worth adding 2 buttons to the emulator itself:
1 - report a problem (you will be taken to the issues page in your browser - https://github.com/shadps4-emu/shadPS4/issues)
2 - report to discord (https://discord.com/invite/bFJxfftGW6)

**Comment by Hermiten** [comment]
Good idea !
To follow

**Comment by Hermiten** [comment]
@DanielSvoboda Hey, maybe for you ? :)

**Comment by GHU7924** [comment]
I really hope that someone will take up the implementation.

At the moment, my personal vision is this (sketched in Paint):

Keyboards Shortcuts

![Sample 1](https://github.com/user-attachments/assets/f3a68de2-cb9c-476d-b79f-97c0711424a8)
![Sample 2](https://github.com/user-attachments/assets/e9fb0073-1c7a-443d-b82a-e63d40e1fcc9)

Send a report

![Report 1](https://github.com/user-attachments/assets/07467804-b2b3-4b1b-b281-346604934916)
![Report 2](https://github.com/user-attachments/assets/a1ddc455-fefc-4ed4-9423-e5e3f766976a)

If someone has their own ideas or options, then please suggest))

P.S. It's also worth changing the name "FPS counter keybinding (F10) should be added to README" to another one.

**Comment by DanielSvoboda** [comment]
I put these buttons in the 'About' and I can make a separate screen as you mentioned for the keys and shortcuts

![ezgif-7-0f0a6ce22a](https://github.com/user-attachments/assets/a2945c6d-060b-47cf-943a-fef76eddc272)

**Comment by GHU7924** [comment]
Your version looks very good too. And maybe that's what you should do with this window, but there should be general links there:

https://github.com/shadps4-emu/shadPS4    -   for example

And I suggested that there should also be an additional button in a prominent place, by clicking on which you can go to a page where you can tell about any problem (Issues) you have with the game, emulator, and so on.

I am looking forward to your vision of the implementation of hotkeys (Keyboards Shortcuts).

And we still need the opinion of other developers about these new features and changes.

P.S. And it may be worth inverting the color of the icons, and replacing the black color with the background color of the window.

![gitinvers](https://github.com/user-attachments/assets/95b0def8-9736-4d49-a66b-8778ff929122)

The picture turned out to be of poor quality, but I think you got the gist.

Edit 2: I also think that the icons should be centered relative to the text, that is, they should be shifted 2 cm (or whatever it takes) to the right.

**Comment by DanielSvoboda** [comment]
I opened the PR as 'Draft', then I'll continue. I had left it without the background as you said, but I decided to fill it in and make everything black and white, because the effect inverts the colors. But with the colors it should look better. Maybe reduce the size of that logo on the left a little. On the keyboard screen I was thinking of putting an image similar to [this PR, but that was undone.](https://github.com/shadps4-emu/shadPS4/pull/308)... and also put the shortcuts on the side

**Comment by GHU7924** [comment]
First of all, I do not know what about YouTube (maybe it is not needed), but I know for sure that there are still links - https://shadps4.net / and https://x.com/shadps4

Secondly, ShadPS4 has the ability to change the theme, so I think the color should be adjusted to the selected theme.
(I have chosen a dark one, so I made a drawing for it.)

![Themes](https://github.com/user-attachments/assets/7d3a3dc7-4217-481b-bacd-cf841e63767e)

Thirdly, if all the links fit, then perhaps the logo on the left should not be touched.

**Comment by DanielSvoboda** [comment]
Does this readme look good?

![image](https://github.com/user-attachments/assets/915b323c-bba0-4658-82b8-5662434399fd)

**Comment by GHU7924** [comment]
>Does this readme look good?

I think so, it is possible to close the issue.

**Comment by Hermiten** [comment]
Fixed #1786

**Comment by GHU7924** [comment]
I apologize.

I know that the topic is closed (let it stay that way), but to me haunted by one point that at this stage of development may be quite useful (in the future it can be removed). 

So as not to spam once again, I will suggest it here.
![info](https://github.com/user-attachments/assets/676e182a-bb7b-4495-9426-bc7443624bab)

@DanielSvoboda If you see the point in this, you can create a new PR without specifying this topic. While the emulator is in the alpha stage, this can be useful and will get rid of some problems, for example, when users post their problems playing on emulators from third-party branches or using different mods that may affect the operation of the emulator.
Whether you take it or not is up to you, I just expressed my thoughts on this matter.

P.S. I do not know if I have taken into account all the points or not, but perhaps this information can be supplemented or corrected in some way.

P.S. If we do this now, this information will become part of shadPS4 v0.5.0, which means that more people will be familiar with this information.

Once again, I apologize for this suddenness.
