### ISSUE TITLE
ROG Ally Z1E - 6GB Allocated VRAM - Bloodborne CUSA03173 1.09

### ISSUE THREAD

**Issue by Oriyen** [shadps4-emu/shadPS4#1390]
Using  Bloodborne CUSA03173 1.09 on ROG Ally Z1E - 6GB Allocated VRAM - I can boot the game get loaded to the intro but once it gets to character creation it just freezes there and never renders the character or enters the name. I have to force close the app. I have the 11.0 modules as well. Attached full shad_log. Not sure how I can fix it. I tried Auto allocation, but it runs out of VRAM before it even loads the game.  I am on the AMD 740M Preview drivers for AFMF2. I did roll them back and try the latest from ASUS, but same issue. 

Now I setup the exact same thing on my PC with a 12GB 3060 i7 and it runs fine. More curious if the issue is driver or shader and if there is anything I can do to address it.
[shad_log.txt](https://github.com/user-attachments/files/17386535/shad_log.txt)

[Render.Vulkan] <Warning> vk_graphics_pipeline.cpp:GraphicsPipeline:92: Rectangle List primitive type is only supported for embedded VS
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CompileModule:419: Compiling fs shader 0x801791be 
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CompileModule:419: Compiling vs shader 0x360418aa 
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CompileModule:419: Compiling fs shader 0x4f4afe5c 
[Render.Vulkan] <Info> vk_pipeline_cache.cpp:CompileModule:419: Compiling vs shader 0xbd0ee4e9 
[Render.Vulkan] <Warning> vk_graphics_pipeline.cpp:GraphicsPipeline:92: Rectangle List primitive type is only supported for embedded VS
[Render.Vulkan] <Error> tile_manager.cpp:TryDetile:394: Unsupported tiled image: R32Sfloat (Depth_MacroTiled)
[Render.Vulkan] <Error> tile_manager.cpp:TryDetile:394: Unsupported tiled image: R32Sfloat (Depth_MacroTiled)
[Render.Vulkan] <Error> tile_manager.cpp:TryDetile:394: Unsupported tiled image: R32Sfloat (Depth_MacroTiled)
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRtcGetCurrentClockLocalTime (nid: ZPD1YOKI+Kw) called, returning zero to 0x9015653f3
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRtcGetTick (nid: 8w-H19ip48I) called, returning zero to 0x90156541b
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRtcSetTick (nid: ueega6v3GUw) called, returning zero to 0x9020ea232
[Render.Vulkan] <Error> tile_manager.cpp:TryDetile:394: Unsupported tiled image: R32Sfloat (Depth_MacroTiled)
[Render.Vulkan] <Error> tile_manager.cpp:TryDetile:394: Unsupported tiled image: R32Sfloat (Depth_MacroTiled)
[Render.Vulkan] <Error> tile_manager.cpp:TryDetile:394: Unsupported tiled image: R32Sfloat (Depth_MacroTiled)
[Render.Vulkan] <Error> tile_manager.cpp:TryDetile:394: Unsupported tiled image: R32Sfloat (Depth_MacroTiled)
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRtcGetCurrentClockLocalTime (nid: ZPD1YOKI+Kw) called, returning zero to 0x9015653f3
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRtcGetTick (nid: 8w-H19ip48I) called, returning zero to 0x90156541b
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sceRtcSetTick (nid: ueega6v3GUw) called, returning zero to 0x9020ea232

**Comment by areeb0768** [comment]
Same issue man...I have tried everything too, but I see videos that it can run on much weaker PCs, it should run on Z1E for sure!

**Comment by RyuSeisuke1992** [comment]
1. Please use this fork with the Full-BB label. This disables a few shaders and is better for middle and low end hardware.
https://github.com/diegolix29/shadPS4/actions

2. I don't know if it makes a difference now, but I have an older AMD driver on the Ally, the 24.8.1 from August. The driver from September with AMFL causes more crashes with ShadPS4. But there is no evidence for this, it's just a feeling.

3. And you should also install the following mod. Because this mod handles the VRAM leak better on devices with less RAM and VRAM. But it is not a guarantee. However, this mod is a game changer for me on the Ally.
https://www.nexusmods.com/bloodborne/mods/114?tab=files

4. And when creating new characters, you should successfully load an extra Savedata beforehand and go back to the main menu, this brings stability to the whole emulator. You can find a ready-made save file on Nexusmods.

PS: 8GB VRAM are better than just 6GB
