### ISSUE TITLE
Update failed.

### ISSUE THREAD

**Issue by VRArt1** [shadps4-emu/shadPS4#1391]
Trying to update shadps4 results in failure. I am currently on version 437ebc1 (2024-10-15 19:34:12) as of writing this the current latest version is 170db22 (2024-10-15 20:03:35). When attempting to use the update function the update files download but then the follow error results within the command line.

```
E:\Dump Drive\Media\Games\[Emulators]\shadps4-win64-qt>Starting Update...
New-Item : An item with the specified name E:\Dump
Drive\Media\Games\[Emulators]\shadps4-win64-qt\user\temp_download_update already exists.
At
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Archive\Microsoft.PowerShell.Archive.psm1:318
char:32
+ ... eatedItem = New-Item -Path $DestinationPath -ItemType Directory -Conf ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceExists: (E:\Dump Drive\M...download_update:String) [New-Item], IOException
    + FullyQualifiedErrorId : DirectoryExist,Microsoft.PowerShell.Commands.NewItemCommand
```

**Comment by DanielSvoboda** [comment]
I'm pretty sure it's because of the folder name [Emulators] , those characters should cause problems [ ]
If you can try putting the emulator in another folder and try updating to make sure that this is what is causing the problem

**Comment by VRArt1** [comment]
Confirmed, that is the cause of it failing to update.

**Comment by DanielSvoboda** [comment]
PowerShell's Expand-Archive function does not handle [ ] characters well.
A temporary workaround is to not save the emulator inside folders with these characters.

A proposed solution would be to change the code to download the update to some Windows temporary folder instead of 'user\temp_download_update'.

To do this, you would have to change the paths in check_update.cpp in DownloadUpdate() and in Install().
I don't have much time for this, if any developer is interested in solving this...

**Comment by Hermiten** [comment]
Fixed
