### ISSUE TITLE
anyone to drop bloodborne with all the patches and mods preinstalled

### ISSUE THREAD

**Issue by MEHDI342** [shadps4-emu/shadPS4#1469]
so we dont have to downlaod and create them one by one, super thanks btw

**Comment by Litnesslegitimate** [comment]
Did you really ask if someone could pre-mod BB so you don't have to do 10 mins (MAX) of work for your free, stolen game to function properly?

You should be embarrassed LOL, how pathetic and lame. Issues are for problems with the emulator, not for lazy bums to shake the "free games" change cup. Gigantic L tbh. Maybe try reddit loser

**Comment by MEHDI342** [comment]
Did your mom abondoned you at birth, or what?

**Comment by Litnesslegitimate** [comment]
That's hysterical and original, it's a wonder you're too dumb to install a couple mods.

Begging for pirated games on the EMU's github isn't a good thing to do because they want to stay distant from such things, you should ask somewhere else and you'll have better luck doing so.

Did your mom drop you after birth or what?

Also, it would be "Did your mom abandon", your English is as poor as your reasoning skills, idiot.

**Comment by MEHDI342** [comment]
It's funny and sad,how much free time you got 😂😂😂

**Comment by Litnesslegitimate** [comment]
It's 4 on a Saturday dude, I'm off work. You should look in the mirror before you try trash-talking though, we're doing the same thing LOL. The only difference if you could be studying, but you're pathetic and I hurt your feelings; so you'd rather whine and argue on AN EMULATORS GITHUB.

Of course you don't have anything to say about the points I made either, because I'm right in every regard.

**Comment by Litnesslegitimate** [comment]
Honestly hop back on duolingo and look at your flashcards lil bro, I'm sick of talking to you and your English really needs some work.

**Comment by polybiusproxy** [comment]
Please cut it out. This is not the place for such discussions.
