### ISSUE TITLE
Shadps4 crashes after obtaining ANY TROPHY in Bloodborne

### ISSUE THREAD

**Issue by zeitar** [shadps4-emu/shadPS4#1503]
Hello, getting crash after trophy obtained. It has been appeared since I starterd game but after killing Reborn I am very annoyed of it. Also I tried to find similar cases but seems that nobody faced this problem. Latest ver
[shad_log.txt](https://github.com/user-attachments/files/17679156/shad_log.txt)

**Comment by CrazyBloo** [comment]
I see that you are using the 2560x1080 patch, can you try without it and see if the crash still happens?

edit: after looking at your log some more it seems like the game ran for a while after the trophy was unlocked, does the game crash when the trophy popup disappears?

**Comment by zeitar** [comment]
> I see that you are using the 2560x1080 patch, can you try without it and see if the crash still happens?
> 
> edit: after looking at your log some more it seems like the game ran for a while after the trophy was unlocked, does the game crash when the trophy popup disappears?

when popup on game freezes and crash

**Comment by zeitar** [comment]
It os not a big deal, but when my game crashes I have to restart game twice to get back my soundfx and keep going.

**Comment by GHU7924** [comment]
First of all, I really see that you are having a critical crash at the end:

>[Debug] Critical renderer_vulkan.cpp:operator():450: Assertion Failed!
>Device lost during waiting for a frame

Secondly, I see that you are using a branch 'MainBB', which does not exactly match what is posted here.

>[Loader] <Info> emulator.cpp:Emulator:61: Starting shadps4 emulator v0.4.1 WIP 
>[Loader] <Info> emulator.cpp:Emulator:62: Revision b6e05e10b642046d37c4f55feb82c15c8fea0a36
>[Loader] <Info> emulator.cpp:Emulator:63: Branch mainBB
>[Loader] <Info> emulator.cpp:Emulator:64: Description b6e05e1

You need to contact the author of the branch 'MainBB' or download his more recent build (if any), perhaps there is already a fix there.

EDIT:

I have the latest official build at the moment, there are no problems, I checked it only because of you.

![555](https://github.com/user-attachments/assets/aeb4e68e-654e-4723-b8a3-4e4f43990e8c)

There is no critical failure. So this is the 'MainBB' build problem.

P.S. Yes, I have a single mod installed that replaces the PS buttons on the Xbox.

**Comment by Hermiten** [comment]
Closing it because we only support issue on shadps4 branch and not fork

**Comment by zeitar** [comment]
it seems I messed up with two different ver of app, with this ver it doesnt crash indeed. Clsd
