### ISSUE TITLE
TROPHY CRASH Reappeared Bloodborne

### ISSUE THREAD

**Issue by zeitar** [shadps4-emu/shadPS4#1511]
Hello again, I setted up latest ver of shadps4 and found out how I can reproduce trophy crash:  gaming without 30 fps fix causes crash, but when i lock fps on 30 with fix game feels good and I can obtain trophy without crash.
![image](https://github.com/user-attachments/assets/5552d205-bde7-49ef-a58a-57fc9bdbc84f)

So Im curious is it my personal hardware problem(8700k +gtx1080) or i can somehow run game without that issue? Log seems to be the same
[shad_log.txt](https://github.com/user-attachments/files/17688725/shad_log.txt)
 Also I recently got recommended sys_modules but it doesnt change anything.

**Comment by zeitar** [comment]
Also Is there any way to quick reset my trophies for testing?

**Comment by GHU7924** [comment]
And hello again))

It seems that this is not the problem, but this build has many other problems that I wrote about (and will add) in #1509. 
I turned on 60 frames per second, but I got the trophies without any problems.

![456](https://github.com/user-attachments/assets/f18abcc3-a99f-4f24-8597-4fa42bbaddd1)

![123](https://github.com/user-attachments/assets/7ecb10be-5414-433e-b013-85b26afafb9d)

![334455](https://github.com/user-attachments/assets/67150e40-cda8-457f-b89b-172fcd416cfd)

https://github.com/user-attachments/assets/5821251d-05d9-4b52-a251-8c531d464cad

I really don't know what your problem might be related to, but maybe you have something with the save file?

Try to start a new game and create a new character with a different name, defeat the Cleric Beast, you can use cheats to speed up the process.

**Comment by GHU7924** [comment]
Try deactivating the Resolution Patch (2560x1080) (21:9 2.37).
Play without any Resolution Patch. See if there will be any changes.

**Comment by GHU7924** [comment]
I updated to build 7ab8515

On the boss of Shadow of Yharnam, after the victory, there was a crash and the emulator closed with an error, I had to go through the boss a second time, the trophy did not display, but at the same time I received it (I may have received it for the first time, but due to a glitch it didn't display).

![nmn](https://github.com/user-attachments/assets/bfd7dca9-f808-45b0-a982-2c20475839a4)

Next, I had these trophies:

https://github.com/user-attachments/assets/d45b6759-47a1-4c61-8346-62ae4dcdc0b1

https://github.com/user-attachments/assets/62b6efd7-b077-48c2-bcb3-7d61ca6e695a

What do you have here?

![TROPHY](https://github.com/user-attachments/assets/f8c33f62-41f4-4e7a-8cce-be4850c600a4)

I don't remember about the values highlighted in red, whether this is an error or not.

![TROPHY2](https://github.com/user-attachments/assets/6343e440-5dc0-4dc8-b2e8-212f25243785)

**Comment by zeitar** [comment]
Same here 
![image](https://github.com/user-attachments/assets/071aaf9e-6127-4768-bc66-a2f93505c4b6)

BTW im testing tesselation ver. and facing same problem with 60 fps KEK. I guess it could be memory crash somehow, i have only 16gb
