### ISSUE TITLE
eldenring save create failure regression

### ISSUE THREAD

**Issue by hgh32** [shadps4-emu/shadPS4#1517]
The problem seems to come from [PR #824](https://github.com/shadps4-emu/shadPS4/pull/824)
[shad_log.txt](https://github.com/user-attachments/files/17698603/shad_log.txt)
![er](https://github.com/user-attachments/assets/1534b3f7-911a-4172-a46f-ddf043150422)
note: This is running on a 8gb dmem build

**Comment by Hermiten** [comment]
We've discussed this and we think it's best to report these problems directly to the relevant PRs so that they can be better taken into account by the developers concerned and better followed up.
I'd like to close the issue and you can report directly here: https://github.com/shadps4-emu/shadPS4/pull/1440 (more-kernel as we can see on your screen)
