### ISSUE TITLE
The version with tessellation has issues with AMD GPUs (Bloodborne).

### ISSUE THREAD

**Issue by ChronoRPG** [shadps4-emu/shadPS4#1543]
Greetings

It turns out that the version with tessellation has issues with AMD graphics cards, as the game crashes when loading a save.

i used this versión: https://github.com/shadps4-emu/shadPS4/actions/runs/11876561268

I’ll provide my log file with Vulkan validation options enabled. Hopefully, the error can be identified. Thank you in advance!

[shad_log.txt](https://github.com/user-attachments/files/17791068/shad_log.txt)

My pc specification:
CPU 5900X AMD
GPU AMD RX 6700 XT
RAM 32GB 3200Mhz

**Comment by baggins183** [comment]
Thanks these are probably the reason for the crash
> Entry-point has conflicting output location assignment at location 0, component 0

Idk why validation on my end didnt show these errors though

**Comment by baggins183** [comment]
https://github.com/shadps4-emu/shadPS4/pull/1528

You can try the update here which is a workaround
not sure if it works, dont have amd

**Comment by Hermiten** [comment]
Hello, thanks for the report.
We've discussed this and we think it's best to report these problems directly to the relevant PRs so that they can be better taken into account by the developers concerned and better followed up.
I'd like to close the issue and you can report directly here: https://github.com/shadps4-emu/shadPS4/pull/1528
