### ISSUE TITLE
[Linux] Can't install games on KDE. Crashes on GNOME when trying to install games

### ISSUE THREAD

**Issue by zedzerosix** [shadps4-emu/shadPS4#1803]
![shad report](https://github.com/user-attachments/assets/7976e72d-7255-4f1c-9e73-578e554b730b)
On KDE plasma 6.2.4 Fedora 41 Kernel 6.11, kde cannot install games. There is no menu bar to install. Switching over to gnome adds a menu bar to install games, however this causes a crash and the game doesn't fully install. Attached is an image on KDE showing the lack of a menu bar. I have tried multiple builds, from multiple forks, and even reverting back to old versions.

**Comment by EmptyVisual** [comment]
I can’t seem to reproduce this issue on KDE Plasma 6.2.4. I tested with the same commit version you’re using (diegos 49931c9) and also on the latest main actual (non-diego).

It looks like the problem is your environment rather than the emulator, as switching to GNOME has demonstrated.

Try creating a new user account and logging in with that—this should reset any conflicting configs in .config or .local that might be causing trouble.

If that doesn’t help, check if you’ve got any widgets related to global menu bars and remove them to see if it makes a difference.

And if you’re still out of stuck, it might be worth asking in the Discord help channel if you haven’t already.

for reference:
![image](https://github.com/user-attachments/assets/a0e4d97a-47ca-4f18-8c18-0ee38be4c75f)

**Comment by zedzerosix** [comment]
> I can’t seem to reproduce this issue on KDE Plasma 6.2.4. I tested with the same commit version you’re using (diegos [49931c9](https://github.com/shadps4-emu/shadPS4/commit/49931c9aedb537e0d8a6b213e2ebbf0012098d55)) and also on the latest main actual (non-diego).
> 
> It looks like the problem is your environment rather than the emulator, as switching to GNOME has demonstrated.
> 
> Try creating a new user account and logging in with that—this should reset any conflicting configs in .config or .local that might be causing trouble.
> 
> If that doesn’t help, check if you’ve got any widgets related to global menu bars and remove them to see if it makes a difference.
> 
> And if you’re still out of stuck, it might be worth asking in the Discord help channel if you haven’t already.
> 
> for reference: ![image](https://private-user-images.githubusercontent.com/4710051/395935161-a0e4d97a-47ca-4f18-8c18-0ee38be4c75f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMTY0OTUsIm5iZiI6MTczNDMxNjE5NSwicGF0aCI6Ii80NzEwMDUxLzM5NTkzNTE2MS1hMGU0ZDk3YS00N2NhLTRmMTgtOGMxOC0wZWUzOGJlNGM3NWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTZUMDIyOTU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjhkMjFiMThjMWY5MzIwYzFiMDYzYjgyYzIxNWU5NTU3ZmVhNDU4YWYwNGJlYjhkM2EyNDI3MTQwNTNlZGYzZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.TQesB1RKAiJWjeHgBcWHEPdsFJ0YCsqa7AGWphFTP4w)

You would be correct, someone in the shadps4 server dug up this issue with someone else. It was my customization. This issue can be closed.

**Comment by adrivn** [comment]
@zedzerosix what was it that prevented the menu from appearing in the global bar? I'm having the same issue (shadps4 appimage on wayland KDE 6.2.4)

**Comment by zedzerosix** [comment]
@adrivn I set the theme to the default Breeze. It brought back the menu bar. From there I did my normal customization 1 by 1 and think it may be the application style under global theme that's causing the issue. I'd reccomend setting your application style to breeze.
