### ISSUE TITLE
About PS4 game Alienation 

### ISSUE THREAD

**Issue by hq5566** [shadps4-emu/shadPS4#1957]
I just downloaded the new version of Shadps4 (0.5.0).

Unfortunately, the PS4 game Alienation is still unable to run. I have been trying to get this game to work since version 0.4.0 but have had no luck so far. On YouTube, someone provided a clue, but no detailed steps were shared.

Back when I was able to debug PS4 games, I attempted to run this game. It appears to have an anti-debug mechanism. On Discord, someone once showed me how to use his/her ASM code to lock ammo. However, I lost contact with that person years ago. I still want to create ASM code for this game, and the PS4 emulator has reignited my interest in trying again.

I currently have a laptop with an RTX 4060 GPU and an AMD 7940HS processor. I really hope to get this game running.

**Comment by Hermiten** [comment]
Like you know because you did a report, the game is not working.
You can update it here: https://github.com/shadps4-emu/shadps4-game-compatibility/issues/10
But we cannot do more here and we will not open an issue for every game.

If your goal is trying to debug it and helping dev, better to come on discord than working on this issue.

Thanks you and Im closing this one
