### ISSUE TITLE
Finding a Fix for Fedora linux

### ISSUE THREAD

**Issue by ryzendew** [shadps4-emu/shadPS4#271]
So fedora linux does not work at all with shadeps4 and i would love if one of the devs could go into matrix and chat with the devs on a possible fix. http://chat.fedoraproject.org/. Every game segfaults even when i compile shadps4

**Comment by whacka** [comment]
It seems that the Qt build does not support Wayland, I haven't tried X11 yet.
When I run the Qt AppImage on Fedora 40 I get the following error.
```
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
Saving new configuration file /var/home/user/Downloads/shadps4-linux-qt-0.1.0/user/config.toml
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: cannot create directory: Read-only file system [/tmp/.mount_Shadpsxxxxxx/usr/bin/game_data/]
Aborted (core dumped)
```

**Comment by anatoliiohorodnyk** [comment]
it is fixed in this PR but it is not merget yet
https://github.com/shadps4-emu/shadPS4/pull/252

**Comment by qurious-pixel** [comment]
Wayland plugins are out-of-scope for PR https://github.com/shadps4-emu/shadPS4/pull/252 , but possible for a follow-up. @whacka

**Comment by anatoliiohorodnyk** [comment]
> Wayland plugins are out-of-scope for PR #252 , but possible for a follow-up.

I expressed myself a little incorrectly, I meant that shadPS4 rather crashed because of a problem "Read-only file system" and it is fixed in your PR

**Comment by DanixUwU** [comment]
Hello guys, how are you?
So i am using Nobara Linux (a Fedora distro with Wayland session) and i was trying to test and experiment the emulator on a HP Pavilion Laptop 15-cs3xxx, but the emulator doesnt work at all, i tried everything i installed dependencies, i tried the Apimage version with qt and without qt, i tried X11 session, i tried the WIP and the 0.1.0 versions, and i even tried to build the emulator my self, still noting.
I also heard from some people on the offical discord server that Arch distros doesnt work at all, and its all very sad, because:
1º- I am dualbooting Windows and Linux on the same computer, and on Windows the emulator is working perfectly fine, without the same errors that i am having on Linux;
2º- I need to use Wayland, because is the only way that i can use my monitor properly, my monitor doesnt work on Windows, it doesnt work on X11, it only works with Wayland;
3º- I dont daily drive Windows, and i am experimenting with new distros, so i dont wanna be forced to use a OS that i dont like and i dont care, just because one emulator doesnt work properly on linux (emulator that HAS support for linux).
So with all this problems and reasons, please, pleaseeeeeeee fix Shadps4 to work properly on Fedora/Arch distros, and on Wayland sessions (even if it's just work on xWayland), seriously i am begging for all of you.
[Video Proving.zip](https://github.com/user-attachments/files/16276228/Video.Proving.zip)

**Comment by Hermiten** [comment]
I think this can be close, @DanixUwU can open a new issue if needed
