### ISSUE TITLE
Github hash for intermediate build

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [shadps4-emu/shadPS4#472]
We have issue with github hash for WIP builds (builds from Pull Requests) - it does not mean nothing.
I see this in CI log - `HEAD is now at 0245ddd Merge 4f9ec8521a75a493fde75726e97c17820f44390d into ad3b6c793c379b0590a6ffed532c6be12b8bb099`
So window bar will contain `0245ddd `. But it should have `4f9ec85`

Here is example how we can get github hashes (but it is Azure, not Github Actions) - https://dev.azure.com/nekotekina/nekotekina/_build/results?buildId=11754&view=logs&j=f31c9f97-4411-58e7-49ac-fc73f645e6b6

**Comment by arodland** [comment]
Getting the SHA of the PR's head in GitHub actions is trivial (it's `github.event.pull_request.head.sha`); the more interesting part is getting that value into cmake and convincing cmake that if it's set it shouldn't use the value from `git_get_head_revision`.

Also it's worth noting that if the PR isn't a fast-forward from main (i.e. other things were merged into main after the branch was started and the branch wasn't rebased), then putting the PR's head into the build info instead of the merge commit is a bit of a lie — if you checked out the PR's head and did your own build, you would be building different code.

**Comment by Hermiten** [comment]
I tried myself and now it's correct so I can close it.

https://github.com/shadps4-emu/shadPS4/commit/b92dc8c714d462362a768d288691c0c6b8059a1b

![image](https://github.com/user-attachments/assets/5d2fce12-bd3b-452f-a725-e22c95ac77b3)
