### ISSUE TITLE
No audio using Linux mint

### ISSUE THREAD

**Issue by illyazru** [shadps4-emu/shadPS4#723]
I don't get any audio using this emulator no matter the game on Linux mint, works fine on windows.
[shad_log.txt](https://github.com/user-attachments/files/16830807/shad_log.txt)

**Comment by Korpyz** [comment]
the same in fedora 40 using the action artifacts. It seems to be a problem with builds in appimage. Compiling from source code makes audio work for me on Fedora.

**Comment by Slug98** [comment]
I hope that this issue is resolved with the appimage eventually. I tried to compile from source but once I tried running the eboot file it just says that there is some exec format error so I would like to simply use the appimage...

**Comment by birthtothunder** [comment]
Can verify sound works when compiled from source

**Comment by emuyia** [comment]
Can also verify, built on Fedora 40 & now have audio.

**Comment by daniilgoss** [comment]
Also confirming that sound started working for me after building from source.

**Comment by Slug98** [comment]
Ok, so I've compiled it from source using the instructions from:
 https://github.com/shadps4-emu/shadPS4/blob/main/documents/building-linux.md

But I cannot verify if audio works since this build doesn't seem to even launch Bloodborne. I'm sure it works on other games as people have verified but I cannot verify for myself as Bloodborne is the only game I own.

I also tried to compile BB-HACKS but I can't seem to be able to locate the url for a git clone of it. Also the zip file that you can get from the main page doesn't seem to work with cmake.

**Comment by fraxalotl** [comment]
@Slug98 i believe you can `git clone -b bb-hacks https://github.com/shadps4-emu/shadPS4.git`, with the `-b` flag denoting a branch,
probably want `--recursive` too i think

**Comment by StevenMiller123** [comment]
@Slug98 @fraxalotl Do not use/compile bb-hacks. It is an ancient build full of hacks that are not needed to run Bloodborne anymore. The latest main builds are enough to test Bloodborne, and should be used when reporting issues with shadPS4. If you have a specific error when trying to run games on the latest main builds, you should post the full error and/or a log so people can help.

**Comment by Slug98** [comment]
@StevenMiller123 
[Shadps4BBTerminalLog.txt](https://github.com/user-attachments/files/16983598/Shadps4BBTerminalLog.txt)

OK, here is what the terminal spits out when I try to run Bloodborne on the main build

**Comment by fraxalotl** [comment]
> @Slug98 @fraxalotl Do not use/compile bb-hacks. It is an ancient build full of hacks that are not needed to run Bloodborne anymore. The latest main builds are enough to test Bloodborne, and should be used when reporting issues with shadPS4. If you have a specific error when trying to run games on the latest main builds, you should post the full error and/or a log so people can help.

Understood, thanks for the guidance :)

**Comment by StevenMiller123** [comment]
@Slug98 please make sure your log type is set to sync. You should also probably update your graphics drivers, as they appear to be far out of date.

**Comment by Slug98** [comment]
@StevenMiller123 OK, I've updated my drivers to the recommended ones on Mint. & changed the log setting to sync here is the new log:
[Shadps4BBTerminalLog2.txt](https://github.com/user-attachments/files/16983844/Shadps4BBTerminalLog2.txt)

**Comment by StevenMiller123** [comment]
@Slug98 Either the problem is an issue with the patches you've applied, or there is some Linux specific bug going on here. Not sure which. Either way, this issue isn't related to the issue reported here, so I would recommend searching through the other Bloodborne-related issues and seeing if your issue is unique. If it is a unique issue, make a separate issue for this (though I doubt this is unique, we have like 30 other issues made specifically about Bloodborne at this point).

**Comment by Slug98** [comment]
@StevenMiller123 No worries, thanks for pointing me in the right direction. I'll keep tinkering with the patches and browse the other issues. 
Thank you.

**Comment by StevenMiller123** [comment]
Oh, and if the crash is fixed by disabling your patches, it should be reported to the patches repository instead of this one.

**Comment by Adamillo** [comment]
Same issue for me with no audio on Linux Mint. Has anyone figured out what's causing this?

**Comment by TheRhysWyrill** [comment]
I'm on Bazzite but this appears to still be an issue, using the latest pre-release build `(shadPS4-2024-10-01-98ea06e)`, the "Play title music" option works for supported titles but nothing seems to have sound when it comes to actual game audio from what I can tell.

**Comment by ngoquang2708** [comment]
Please test this https://github.com/shadps4-emu/shadPS4/actions/runs/11119129430 and report to https://github.com/shadps4-emu/shadPS4/pull/1177.

**Comment by Hermiten** [comment]
This is fixed
