### ISSUE TITLE
AMD - Immediate crash in game

### ISSUE THREAD

**Issue by valytica-mattb** [shadps4-emu/shadPS4#957]
I'm able to get in game, however Bloodborne crashes to desktop with a driver crash as soon as I make any character movement.

GPU: 7900XTX
CPU: 7800X3D
Driver: 24.8.1
Build: Latest Windows-Qt #2625

sfx removed
applied: Bloodborne Remaster Project
log attached

Keen to help getting AMD up to scratch, let me know if I can do anything to help!

[shad_log.txt](https://github.com/user-attachments/files/17025338/shad_log.txt)

**Comment by danimroca** [comment]
To any devs reading this I assume you are already aware, but this is caused because AMD cards (at least rx6000 and rx7000 series) do not have support for d24_unorm_s8_uint aka D24UnormS8Uint, so when it tries to get the alternative VK format it crashes because it's not in the drivers.

I'm suffering the same issue, I tried replacing it and making the GetAlternativeFormat method to return eD32SfloatS8Uint instead and I get further than the error OP mentioned, but I get different problems. I'm not a c++ dev so I can't fix the rest of the issues sadly...

**Comment by raphaelthegreat** [comment]
Bloodborne does not use D24S8 depth format. The error you see is just emulator querying properties of all formats. The cause is something different probably

**Comment by danimroca** [comment]
@raphaelthegreat I didn't say BB uses it, but that AMD doesn't support it and it causes the error.

I don't know if this error prevents the emulator from running the game entirely or it's more of a "fails but continues" kinda thing, because even if I set it to return eD32SfloatS8Uint the game won't get to the menu, I think I get memory loading errors later on, I can provide logs here or on a different ticket.

**Comment by josephraporute** [comment]
Hi, having this issue here too. 3-5+ people on the 7000 series cards. I am more than willing to help test anything necessary for the RDNA3 platform to get it working alongside the SFX fixes, whatever you may need please let me know, I am no coder but I can help with any testing necessary

**Comment by Johnwrnd** [comment]
This is interesting because I have the exact same hardware as shown in the original post and the game runs great apart from vertex explosions which ruins the gameplay after a while and SFX which does not work at all for us AMD users. If I can be of any help by providing information I will be happy to provide it. The only difference I see is that I'm not using the Bloodborne Remaster Project mod but the FPS Boost instead.

**Comment by Hermiten** [comment]
Cleaning bloodborne issue, please try again on lastest version, check if it's fixed for you and if not, please check if issue already exist on github before doing a new one.

**Comment by tiagogrunge** [comment]
It worked here. The game now pass the character creation in my 7900 XTX. I have sound only in cutscenes. No sound on gameplay.
